version: "3.8"

services:
  php:
    build: .
    container_name: php83_app
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: phptraining
      MYSQL_USER: myphpuser
      MYSQL_PASSWORD: Raju0812@2025
      MYSQL_ROOT_PASSWORD: Shaloo0812@2025
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
